CREATE DATABASE IF NOT EXISTS `picocmdb-model` DEFAULT CHARACTER SET utf8
;
USE `picocmdb-model`
;

SET FOREIGN_KEY_CHECKS=0 
;

DROP TABLE IF EXISTS `role` CASCADE
;

CREATE TABLE `role`
(
	`id` NVARCHAR(50) NOT NULL,
	`description` NVARCHAR(200) 	 NULL,
	`is_system` BIT(1) NOT NULL,
	CONSTRAINT `PK_role` PRIMARY KEY (`id` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1 
;
