CREATE DATABASE IF NOT EXISTS `picocmdb` DEFAULT CHARACTER SET utf8
;
USE `picocmdb`
;

SET FOREIGN_KEY_CHECKS=0 
;

DROP TABLE IF EXISTS `Role` CASCADE
;

CREATE TABLE `Role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` NVARCHAR(50) 	 NULL,
	`description` NVARCHAR(100) 	 NULL,
	CONSTRAINT `PK_Role` PRIMARY KEY (`id` ASC)
)

;

ALTER TABLE `Role` 
 ADD CONSTRAINT `UQ_name` UNIQUE (`name` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
